--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/ilya/walls/wallhaven-011xo9.png"

-- Special
background="#010101"
foreground="#ebecea"
cursor="#ebecea"

-- Colors
color0="#010101"
color1="#77C0DE"
color2="#6DCFF6"
color3="#999998"
color4="#FDC689"
color5="#D4C9AB"
color6="#AACFD4"
color7="#ebecea"
color8="#a4a5a3"
color9="#77C0DE"
color10="#6DCFF6"
color11="#999998"
color12="#FDC689"
color13="#D4C9AB"
color14="#AACFD4"
color15="#ebecea"
