# Shell variables
# Generated by 'wal'
wallpaper='/home/ilya/.config/sway/wallpaper.png'

# Special
background='#000514'
foreground='#9ca7b5'
cursor='#9ca7b5'

# Colors
color0='#000514'
color1='#192E47'
color2='#243851'
color3='#2D425C'
color4='#344C67'
color5='#44454F'
color6='#445B76'
color7='#9ca7b5'
color8='#6d747e'
color9='#192E47'
color10='#243851'
color11='#2D425C'
color12='#344C67'
color13='#44454F'
color14='#445B76'
color15='#9ca7b5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
