# Shell variables
# Generated by 'wal'
wallpaper='/home/ilya/walls/wallhaven-011xo9.png'

# Special
background='#010101'
foreground='#ebecea'
cursor='#ebecea'

# Colors
color0='#010101'
color1='#77C0DE'
color2='#6DCFF6'
color3='#999998'
color4='#FDC689'
color5='#D4C9AB'
color6='#AACFD4'
color7='#ebecea'
color8='#a4a5a3'
color9='#77C0DE'
color10='#6DCFF6'
color11='#999998'
color12='#FDC689'
color13='#D4C9AB'
color14='#AACFD4'
color15='#ebecea'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
