--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/ilya/walls/pexels-arist-creathrive-1183525-2253573.jpg"

-- Special
background="#0C292D"
foreground="#dde0e2"
cursor="#dde0e2"

-- Colors
color0="#0C292D"
color1="#3F9AAE"
color2="#6398A2"
color3="#96ABAE"
color4="#C2B9AC"
color5="#9BBAC6"
color6="#AFC8CE"
color7="#dde0e2"
color8="#9a9c9e"
color9="#3F9AAE"
color10="#6398A2"
color11="#96ABAE"
color12="#C2B9AC"
color13="#9BBAC6"
color14="#AFC8CE"
color15="#dde0e2"
