# Shell variables
# Generated by 'wal'
wallpaper='/home/ilya/walls/ameer-basheer-gV6taBJuBTk-unsplash.jpg'

# Special
background='#020207'
foreground='#a6bed7'
cursor='#a6bed7'

# Colors
color0='#020207'
color1='#5D3858'
color2='#214872'
color3='#A04659'
color4='#1F5B98'
color5='#4F6DA3'
color6='#B2738C'
color7='#a6bed7'
color8='#748596'
color9='#5D3858'
color10='#214872'
color11='#A04659'
color12='#1F5B98'
color13='#4F6DA3'
color14='#B2738C'
color15='#a6bed7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
