--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/ilya/walls/ameer-basheer-gV6taBJuBTk-unsplash.jpg"

-- Special
background="#020207"
foreground="#a6bed7"
cursor="#a6bed7"

-- Colors
color0="#020207"
color1="#5D3858"
color2="#214872"
color3="#A04659"
color4="#1F5B98"
color5="#4F6DA3"
color6="#B2738C"
color7="#a6bed7"
color8="#748596"
color9="#5D3858"
color10="#214872"
color11="#A04659"
color12="#1F5B98"
color13="#4F6DA3"
color14="#B2738C"
color15="#a6bed7"
