# Shell variables
# Generated by 'wal'
wallpaper='/home/ilya/walls/pexels-arist-creathrive-1183525-2253573.jpg'

# Special
background='#0C292D'
foreground='#dde0e2'
cursor='#dde0e2'

# Colors
color0='#0C292D'
color1='#3F9AAE'
color2='#6398A2'
color3='#96ABAE'
color4='#C2B9AC'
color5='#9BBAC6'
color6='#AFC8CE'
color7='#dde0e2'
color8='#9a9c9e'
color9='#3F9AAE'
color10='#6398A2'
color11='#96ABAE'
color12='#C2B9AC'
color13='#9BBAC6'
color14='#AFC8CE'
color15='#dde0e2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
