# theme = "default"
theme = "catppuccin_frappe"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
# true-color = true
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

# [editor]
# true-color = true
# color-modes = true
# bufferline = "always"

[editor.lsp]
display-messages = true

# [editor.whitespace.render]
# space = "all"
# tab = "all"
# nbsp = "all"
# newline = "none"

# [editor]
# true-color = true
# color-modes = true
# bufferline = "always"
#
# [editor.lsp]
# display-messages = true
#
# [editor.whitespace.render]
# space = "all"
# tab = "all"
# nbsp = "all"
# newline = "all"
