[[session]]
name = "lazyvim"
path = "~/dotfiles/available/lazyvim/dot-config/nvim"
startup_command = "nvim"
preview_command = "eza --tree ~/dotfiles/available/lazyvim/dot-config/nvim"

[[session]]
name = "DOT"
path = "~/dotfiles/"
# startup_command = "lazygit"
preview_command = "eza --icons=always --color=always --long --header --time modified --git --git-ignore --no-user --no-permissions --group-directories-first ~/dotfiles"
windows = ["helix"]

[[session]]
name = "Music"
path = "~/Music/"
startup_command = "yatzi"
preview_command = "eza --icons=always --color=always --long --header --time modified --git --git-ignore --no-user --no-permissions --group-directories-first ~/Music/"

#
# WINDOWS
#

[[window]]
name = "nvim"
startup_script = "nvim"

[[window]]
name = "helix"
startup_script = "hx ."
