theme = "default"

[editor]
true-color = true
color-modes = true
bufferline = "always"

[editor.lsp]
display-messages = true

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "all"
newline = "all"
